[package]
name = "uets"
version = "0.1.0"
edition = "2021"

[dependencies]
adw = { package = "libadwaita", version = "0.7", features = ["v1_2"] }
gtk = { package = "gtk4", version = "0.9", features = ["gnome_43"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
